# Generated by Django 4.0.6 on 2022-08-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Movies', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
