# Generated by Django 4.0.6 on 2022-09-04 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlatforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=150)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('platforms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchList', to='watchlistApp.streamplatforms')),
            ],
            options={
                'verbose_name': 'WatchList',
                'verbose_name_plural': "WatchList's",
            },
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
