# Generated by Django 4.0.6 on 2022-09-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistApp', '0004_reviews_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='numberOfRating',
            field=models.IntegerField(default=0),
        ),
    ]
